spring.application.name=product-backend
#JDBC=does actual communication between java and databases,(is a translator/bridge)
#mysql-driver-helps jdbc understands mysql
#jpa-maps java objects to database tables ,uses ORM to map the objects in rows and tables
#it is a interface/rulebook-instead of writing sql queries we create java objects and it does sql queries internally

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
#meaning whatever i write inside entity class automatically create sql queries internaly
#ddl-automatically performs data-definition language & updates or creates tables
spring.jpa.show-sql=true
#meaning show sql queries whatver hibernate does internally
spring.jpa.properties.hibernate.format_sql=true
#sql queries show in format structure


